# **Task 1**

In [1]:
import numpy as np

In [2]:
stats = np.array([[180, 75, 30], [175, 68, 45], [190, 82, 25], [165, 60, 50], [160, 78, 55]])
stats

array([[180,  75,  30],
       [175,  68,  45],
       [190,  82,  25],
       [165,  60,  50],
       [160,  78,  55]])

In [3]:
maxi = np.argmax(stats[:,2])
maxi

np.int64(4)

In [4]:
stats[maxi][1] = 60
stats

array([[180,  75,  30],
       [175,  68,  45],
       [190,  82,  25],
       [165,  60,  50],
       [160,  60,  55]])

In [5]:
stats = np.append(stats, [[150, 40,40]], axis = 0)
stats

array([[180,  75,  30],
       [175,  68,  45],
       [190,  82,  25],
       [165,  60,  50],
       [160,  60,  55],
       [150,  40,  40]])

In [6]:
i = 2
stats = np.insert(stats, i, [[160, 50,50]], axis = 0)
stats

array([[180,  75,  30],
       [175,  68,  45],
       [160,  50,  50],
       [190,  82,  25],
       [165,  60,  50],
       [160,  60,  55],
       [150,  40,  40]])

In [7]:
mini = np.argmin(stats[:,2])
mini

np.int64(3)

In [8]:
stats = np.delete(stats, mini, axis = 0)
stats

array([[180,  75,  30],
       [175,  68,  45],
       [160,  50,  50],
       [165,  60,  50],
       [160,  60,  55],
       [150,  40,  40]])

# **Task 2**

In [9]:
purchase = np.random.randint(10,100,5)
counts = np.random.randint(1,10,5)

In [10]:
pshallow = purchase.view()
cdeep = counts.copy()

In [11]:
combined = np.concatenate([pshallow, cdeep])
combined

array([72, 68, 28, 57, 37,  1,  2,  2,  6,  1], dtype=int32)

In [12]:
lesser = combined[combined < 20]
greater = combined[combined >= 20]
print(lesser, greater)

[1 2 2 6 1] [72 68 28 57 37]


In [13]:
purchase[0] = 5
counts[0] = 50
print(purchase, pshallow, '\n', counts, cdeep)

[ 5 68 28 57 37] [ 5 68 28 57 37] 
 [50  2  2  6  1] [1 2 2 6 1]


# **Bonus Task:** Advanced Git Commands

1. *git stash* - This command would be useful if we want to switch between branches but we don't want to yet commit changes of branch we're in.
2. *git stash list*
3. *git stash apply* - Stashed changes are applied on current branch
4. *git stash drop @stash{n}* - Before executing this command, keep it in mind that it is irreversible and make sure you use corrent stash id.