# **Lab 01**

### *Task 01*

In [1]:
import numpy as np

In [18]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
arr2 = arr.reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
arr2[:,-1] = 0 
arr2

array([[ 1,  2,  3,  4,  0],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14,  0],
       [16, 17, 18, 19,  0]])

In [21]:
flat = arr2.flatten()
flat

array([ 1,  2,  3,  4,  0,  6,  7,  8,  9,  0, 11, 12, 13, 14,  0, 16, 17,
       18, 19,  0])

### *Task 02*

In [22]:
array = np.random.randint(10,51,(5,5))
array

array([[23, 24, 50, 29, 19],
       [24, 42, 43, 32, 17],
       [19, 31, 43, 34, 18],
       [24, 48, 46, 49, 35],
       [43, 11, 18, 45, 17]], dtype=int32)

In [23]:
meanr = np.mean(array, axis = 1)
sumr = np.sum(array, axis = 1)
maxr = np.max(array, axis = 1)
minr = np.min(array, axis = 1)
print(meanr, sumr, maxr, minr)

[29.  31.6 29.  40.4 26.8] [145 158 145 202 134] [50 43 43 49 45] [19 17 18 24 11]


In [24]:
meanr = np.mean(array, axis = 0)
sumr = np.sum(array, axis = 0)
maxr = np.max(array, axis = 0)
minr = np.min(array, axis = 0)
print(meanr, sumr, maxr, minr)

[26.6 31.2 40.  37.8 21.2] [133 156 200 189 106] [43 48 50 49 35] [19 11 18 29 17]


### *Task 03*

In [25]:
mat = np.eye(4)
mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
mat[np.diag_indices_from(mat)] += 5
mat

array([[6., 0., 0., 0.],
       [0., 6., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 6.]])

In [27]:
mat[-1,:] = 1
mat

array([[6., 0., 0., 0.],
       [0., 6., 0., 0.],
       [0., 0., 6., 0.],
       [1., 1., 1., 1.]])

### *Task 04*

In [28]:
four = np.random.randint(0, 21, 15)
four

array([16, 17,  3,  5,  6,  8, 14, 17, 16, 13,  1, 20,  1, 12, 10],
      dtype=int32)

In [29]:
uniq = np.unique(four, return_counts = True)
uniq

(array([ 1,  3,  5,  6,  8, 10, 12, 13, 14, 16, 17, 20], dtype=int32),
 array([2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1]))

In [30]:
gr = np.where(four > 10)[0]
gr

array([ 0,  1,  6,  7,  8,  9, 11, 13])

### *Task 05*

In [31]:
fif = np.random.rand(3,4)
fif

array([[0.62823054, 0.57481061, 0.61586157, 0.23872191],
       [0.73315458, 0.07929288, 0.19803528, 0.29375038],
       [0.2246351 , 0.30222842, 0.78171307, 0.18273431]])

In [32]:
rou = np.round(fif, 2)
rou

array([[0.63, 0.57, 0.62, 0.24],
       [0.73, 0.08, 0.2 , 0.29],
       [0.22, 0.3 , 0.78, 0.18]])

In [33]:
rou[:,1] = 0.5
